add_test
Albert-SA/js-windows pull request #1
Opened 2023-11-30 09:15 UTC by Albert-SA

2023-11-30 17:37 UTC, Albert-SA commented
js-native-windows.netlify.app](https://js-native-windows.netlify.app/

2023-11-30 18:30 UTC, andrey-kudinov commented
> https://js-native-windows.netlify.app/

нетлифай должен автоматически подключиться и делать деплой превью

странно что ссылка сама не появилась

2023-11-30 18:33 UTC, andrey-kudinov requested changes
Хорошая работа 👍
Есть несколько моментов, которые можно улучшить
Посмотри пж в комментариях

2023-11-30 18:33 UTC, andrey-kudinov commented on dist/assets/1-e33dc523.png
директория дист должна быть в `gitignore`

удали пожалуйста ее из ПР и после этого добавь ее в `gitignore`

2023-11-30 18:33 UTC, andrey-kudinov commented on package-lock.json
оба файла - package-lock и yarn.lock - не должны быть в проекте

надо пользоваться или nmp или yarn

в документации к проекту я указал yarn, давай им пользоваться

удали пожалуйста package-lock

2023-11-30 18:33 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +      close = document.querySelector(closeSelector);
Старайся пж не использовать синтаксис чз запятую
Считается, что это сложнее для чтения кода

2023-11-30 18:33 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +    const trigger = document.querySelectorAll(triggerSelector),
Хочу обратить твоё внимание на нейминг
В твоём случае здесь массив элементов, поэтому trigger**s**

2023-11-30 18:33 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +    });
Здесь так же хотел бы обратить внимание на нейминг
Старайся пж придерживаться более говорящего неймига
Тогда код будет более читабельный
На сложный проектах это играет большую роль
```
triggers.forEach(trigger => ...
cards.forEach(card => ...
books.forEach(book => ...
```

2023-11-30 18:33 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +        document.body.style.overflow = '';
```
modal.style.display = 'none';
document.body.style.overflow = '';
```
Эти две строчки повторяются несколько раз, вынеси пж их в отдельную функцию `closeModal` и переиспользуй её
Это будет соответствовать принципу [DRY](https://ru.wikipedia.org/wiki/Don’t_repeat_yourself)
Так же добавь пж закрытие модального окна по клавише `escape`

2023-11-30 18:33 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +    setTimeout(function () {
Давай попробуем в этом проекте писать исключительно стрелочные функции
Во-первых, практика рефакторинга (довольно простого)
Во-вторых, на мой взгляд, это позволит лучше читать код, так как он будет последовательный
Всегда понятно что за функция будет вызвана, так как она до этого объявлена
Так же на мой взгляд это современнее

2023-12-01 05:28 UTC, Albert-SA commented on src/js/modules/modals.js
> +      close = document.querySelector(closeSelector);
ок

2023-12-01 05:28 UTC, Albert-SA commented on src/js/modules/modals.js
> +    const trigger = document.querySelectorAll(triggerSelector),
щл

2023-12-01 05:29 UTC, Albert-SA commented on src/js/modules/modals.js
> +    });
ok

2023-12-01 06:05 UTC, Albert-SA commented on dist/assets/1-e33dc523.png
ok

2023-12-01 06:05 UTC, Albert-SA commented on package-lock.json
ok

2023-12-01 08:38 UTC, Albert-SA commented on src/js/modules/modals.js
> +        document.body.style.overflow = '';
Согласен, учитывая если кол-во действий будет увеличиваться то логично

2023-12-01 16:53 UTC, Albert-SA commented on src/js/modules/modals.js
> +    setTimeout(function () {
ok

2023-12-01 18:46 UTC, andrey-kudinov commented on .vscode/settings.json
Этот файл так же лучше удалить из ПР и положить в гитигнор
В проекте обычно работает целая команда и не у всех vs code и не всем нужны настройки как у тебя

2023-12-01 18:46 UTC, andrey-kudinov commented on index.html
> +  <script src="script.js"></script>
Что это за файл? У нас я вижу main.js главный

2023-12-02 04:51 UTC, Albert-SA commented on index.html
> +  <script src="script.js"></script>
В курсе так было, подумал что так надо) Как ни странно скрипт подтянулся - хоть и другое имя.

2023-12-02 10:41 UTC, merged