02_add_tabs
Albert-SA/js-windows pull request #2
Opened 2023-12-02 11:54 UTC by Albert-SA

2023-12-03 06:18 UTC, andrey-kudinov requested changes
Хорошо получилось 👍
Я написал несколько моментов как можно ещё улучшить

2023-12-03 06:18 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +const tabs = (headerSelector, tabsSelector, contentsSelector, activeClass) => {
Старайся пж не использовать в функции больше 2-3 аргументов
Это делает её сложной в использовании
Особенно, если часть аргументов опциональные
Так же для стороннего человека будет не понятно для чего все эти аргументы
Если вложить объект как аргумент, станет всё значительно читабельнее

Материал по этому вопросу (2-3 минуты):
https://github.com/ryanmcdermott/clean-code-javascript#function-arguments-2-or-fewer-ideally

2023-12-03 06:18 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +  const tabsSec = document.querySelectorAll(tabsSelector);
это не селектор, это массив элементов
можно просто tabs

2023-12-03 06:18 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +      tabsSec.forEach((tab, item) => {
второй аргумент не item а index - порядковый номер

2023-12-03 06:18 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +  const showTabContent = (item = 0) => {
здесь тоже index

2023-12-03 08:59 UTC, Albert-SA commented on src/js/modules/tabs.js
> +  const tabsSec = document.querySelectorAll(tabsSelector);
переименовал в tabElems

2023-12-04 04:48 UTC, andrey-kudinov commented on src/js/modules/tabs.js
> +};
в целом гуд

по правилам доступности действительно советуют сделать стрелками

https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/

в твоем случае немного переусложнил так как у тебя табы уже являются ссылками и по ним можно навигироваться с клавиатуры через tab или tab+shift

но нельзя активировать таб через enter

возможно просто слушатель на эту клавишу стоит повесить, иначе сейчас есть две навигации - с клавишь влево-вправо и с клавишь tab/tab+shift, и фокус у них не синхронный

так же для варианта с enter не забудь пожалуйста переиспользовать код

2023-12-07 15:25 UTC, Albert-SA commented on src/js/modules/tabs.js
> +};
сделал, выделил отдельную функцию selectTab

2023-12-07 15:45 UTC, merged