04_add_windows
Albert-SA/js-windows pull request #4
Opened 2023-12-08 19:29 UTC by Albert-SA

2023-12-10 08:24 UTC, andrey-kudinov requested changes
Хорошая работа 👍
Однако я заметил, что навигация с клавиатуры не работает с чекбоксами/радио-баттонами

Всё дело в том что их не совсем правильно сделали
Ошибка маленькая и я могу сказать где, но будет здорово если посмотришь эту статью и сам её найдёшь

https://ishadeed.com/article/hiding-web/

Более того это ответит на вопрос с собеседования "Скрытие элементов" и даже расскажет про подводные камни и нюансы

Так же при необходимости пж настрой парой строчек в CSS focus или focus-visible для всех интерактивных элементов

2023-12-10 08:24 UTC, andrey-kudinov commented on src/js/modules/changeModalState.js
> +            break;
Здесь мы с тобой столкнулись с принципиальной ошибкой в вёрстке
Используются инпуты с типом `checkbox`, и с помощью JS из них делают поведение инпутов с типом `radio`

Посмотри пж как работают инпуты с типом`radio`, замени в верстке тип на них и дай им нужное `value`
Эти нехитрые действия позволят удалить из js кучу строчек кода)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/radio
https://doka.guide/html/input/

2023-12-11 15:58 UTC, Albert-SA commented on src/js/modules/changeModalState.js
> +            break;
ok

2023-12-11 18:00 UTC, andrey-kudinov commented on index.html
> +        <button class="button popup_calc_button" aria-hidden="true">Далее</button>
Если скроешь эту кнопку, то скрин ридер ее не увидит и для пользователя она будет не доступна

2023-12-11 18:00 UTC, andrey-kudinov commented on index.html
> +          <span class="checkbox-custom" id="cold" tabindex="0"></span>
это не совсем тот вариант который нужен

автор вёрстки использовал неправильное скрытие нативных инпутов

в статье этот момент есть, посмотри пожалуйста вторым взглядом на статью и данный код

2023-12-11 18:00 UTC, andrey-kudinov commented on index.html
> +          <input class="checkbox" type="radio" value="Холодное" name="checkbox-test" hidden>
я думаю данное решение скроет этот инпут от скрин ридеров и навигации с клавиатуры

будет лучше найти другое решение

2023-12-11 18:00 UTC, andrey-kudinov commented on src/assets/css/style.css
> +}
посмотри каким решением инпуты скрыты на данный момент

2023-12-14 15:40 UTC, merged